// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Models;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(VnmDbContext))]
    [Migration("20260402201441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Repositories.Models.ConsumptionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("InverterInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Power")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_ConsumptionReadings_AddressId");

                    b.HasIndex(new[] { "InverterInfoId" }, "IX_ConsumptionReadings_InverterInfoId");

                    b.ToTable("ConsumptionReadings");
                });

            modelBuilder.Entity("Repositories.Models.DailyEnergyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ConsumedKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("Day")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DeficitKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("InverterInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetKwh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("NetPerAddressKwh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ProducedKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SurplusKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_DailyEnergyBalances_AddressId");

                    b.HasIndex(new[] { "InverterInfoId" }, "IX_DailyEnergyBalances_InverterInfoId");

                    b.ToTable("DailyEnergyBalances");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_InverterInfos_AddressId");

                    b.ToTable("InverterInfos");
                });

            modelBuilder.Entity("Repositories.Models.InverterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Current")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InverterInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Power")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Voltage")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InverterInfoId" }, "IX_InverterReadings_InverterInfoId");

                    b.ToTable("InverterReadings");
                });

            modelBuilder.Entity("Repositories.Models.ProviderSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AcceptedKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Day")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnergyCreditKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("InjectedKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("MonetaryCredit")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RatePerKwh")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("SettlementMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_ProviderSettlements_AddressId");

                    b.ToTable("ProviderSettlements");
                });

            modelBuilder.Entity("Repositories.Models.TransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DestinationAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SettlementMode")
                        .HasColumnType("int");

                    b.Property<int>("SourceAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("Repositories.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("Repositories.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("Repositories.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Models.ConsumptionReading", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("ConsumptionReadings")
                        .HasForeignKey("AddressId");

                    b.HasOne("Repositories.Models.InverterInfo", "InverterInfo")
                        .WithMany("ConsumptionReadings")
                        .HasForeignKey("InverterInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsumptionReadings_InverterInfos");

                    b.Navigation("Address");

                    b.Navigation("InverterInfo");
                });

            modelBuilder.Entity("Repositories.Models.DailyEnergyBalance", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("DailyEnergyBalances")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DailyEnergyBalances_Addresses");

                    b.HasOne("Repositories.Models.InverterInfo", "InverterInfo")
                        .WithMany("DailyEnergyBalances")
                        .HasForeignKey("InverterInfoId")
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("InverterInfo");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("InverterInfos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.InverterReading", b =>
                {
                    b.HasOne("Repositories.Models.InverterInfo", "InverterInfo")
                        .WithMany("InverterReadings")
                        .HasForeignKey("InverterInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InverterReadings_InverterInfos");

                    b.Navigation("InverterInfo");
                });

            modelBuilder.Entity("Repositories.Models.ProviderSettlement", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("ProviderSettlements")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK_ProviderSettlements_Addresses");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.Address", b =>
                {
                    b.Navigation("ConsumptionReadings");

                    b.Navigation("DailyEnergyBalances");

                    b.Navigation("InverterInfos");

                    b.Navigation("ProviderSettlements");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.Navigation("ConsumptionReadings");

                    b.Navigation("DailyEnergyBalances");

                    b.Navigation("InverterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
