// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Models;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(VnmDbContext))]
    [Migration("20260503203023_FixAmountAtExecutionTypo")]
    partial class FixAmountAtExecutionTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Repositories.Models.ConsumptionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_ConsumptionReadings_AddressId");

                    b.ToTable("ConsumptionReadings");
                });

            modelBuilder.Entity("Repositories.Models.DailyEnergyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConsumedKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeficitKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int?>("InverterInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF__DailyEner__Inver__628FA481");

                    b.Property<decimal>("NetKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("NetPerAddressKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("ProducedKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SurplusKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_DailyEnergyBalances_AddressId");

                    b.HasIndex(new[] { "InverterInfoId" }, "IX_DailyEnergyBalances_InverterInfoId");

                    b.ToTable("DailyEnergyBalances");
                });

            modelBuilder.Entity("Repositories.Models.DestinationTransferRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationAddressId")
                        .HasColumnType("int");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDailyKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SourceTransferPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WeightPercent")
                        .HasColumnType("decimal(18, 5)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DestinationAddressId" }, "IX_DestinationTransferRules_DestinationAddressId");

                    b.HasIndex(new[] { "SourceTransferPolicyId" }, "IX_DestinationTransferRules_SourceTransferPolicyId");

                    b.ToTable("DestinationTransferRules");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_InverterInfos_AddressId");

                    b.ToTable("InverterInfos");
                });

            modelBuilder.Entity("Repositories.Models.InverterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("InverterInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18, 5)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex(new[] { "InverterInfoId" }, "IX_InverterReadings_InverterInfoId");

                    b.ToTable("InverterReadings");
                });

            modelBuilder.Entity("Repositories.Models.ProviderSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcceptedKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergyCreditKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("InjectedKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("MonetaryCredit")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("SettlementMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AddressId" }, "IX_ProviderSettlements_AddressId");

                    b.ToTable("ProviderSettlements");
                });

            modelBuilder.Entity("Repositories.Models.SourceTransferPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SourceAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SourceAddressId" }, "IX_SourceTransferPolicies_SourceAddressId");

                    b.ToTable("SourceTransferPolicies");
                });

            modelBuilder.Entity("Repositories.Models.SourceTransferSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionMode")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RepeatEveryUnit")
                        .HasColumnType("int");

                    b.Property<int?>("RepeatEveryValue")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<int>("SourceTransferPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TimeOfDayUtc")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SourceTransferPolicyId" }, "IX_SourceTransferSchedules_SourceTransferPolicyId");

                    b.ToTable("SourceTransferSchedules");
                });

            modelBuilder.Entity("Repositories.Models.TransferLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<DateOnly>("BalanceDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SourceAddressId")
                        .HasColumnType("int");

                    b.Property<int>("TransferWorkflowId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExecutedAtUtc" }, "IX_TransferLedgerEntries_ExecutedAtUtc");

                    b.HasIndex(new[] { "TransferWorkflowId" }, "IX_TransferLedgerEntries_TransferWorkflowId");

                    b.ToTable("TransferLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.TransferWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountAtExecutionKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountKwh")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("AppliedDistributionMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("BalanceDayUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationAddressId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DestinationDeficitKwhAtExecution")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("DestinationDeficitKwhAtWorkflow")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int?>("DestinationTransferRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SettlementMode")
                        .HasColumnType("int");

                    b.Property<int>("SourceAddressId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SourceSurplusKwhAtExecution")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<decimal>("SourceSurplusKwhAtWorkflow")
                        .HasColumnType("decimal(18, 5)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WeightPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DestinationAddressId" }, "IX_TransferWorkflow_DestinationAddressId");

                    b.HasIndex(new[] { "DestinationTransferRuleId" }, "IX_TransferWorkflow_DestinationTransferRuleId");

                    b.HasIndex(new[] { "SourceAddressId" }, "IX_TransferWorkflow_SourceAddressId");

                    b.ToTable("TransferWorkflow", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.TransferWorkflowStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<int>("TransferWorkflowId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAtUtc" }, "IX_TransferWorkflowStatusHistory_CreatedAtUtc");

                    b.HasIndex(new[] { "TransferWorkflowId" }, "IX_TransferWorkflowStatusHistory_TransferWorkflowId");

                    b.ToTable("TransferWorkflowStatusHistory", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("Repositories.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("Repositories.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("Repositories.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Models.ConsumptionReading", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("ConsumptionReadings")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.DailyEnergyBalance", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("DailyEnergyBalances")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DailyEnergyBalances_Addresses");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.DestinationTransferRule", b =>
                {
                    b.HasOne("Repositories.Models.Address", "DestinationAddress")
                        .WithMany("DestinationTransferRules")
                        .HasForeignKey("DestinationAddressId")
                        .IsRequired();

                    b.HasOne("Repositories.Models.SourceTransferPolicy", "SourceTransferPolicy")
                        .WithMany("DestinationTransferRules")
                        .HasForeignKey("SourceTransferPolicyId")
                        .IsRequired();

                    b.Navigation("DestinationAddress");

                    b.Navigation("SourceTransferPolicy");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("InverterInfos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.InverterReading", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("InverterReadings")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_InverterReadings_Addresses");

                    b.HasOne("Repositories.Models.InverterInfo", "InverterInfo")
                        .WithMany("InverterReadings")
                        .HasForeignKey("InverterInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InverterReadings_InverterInfos");

                    b.Navigation("Address");

                    b.Navigation("InverterInfo");
                });

            modelBuilder.Entity("Repositories.Models.ProviderSettlement", b =>
                {
                    b.HasOne("Repositories.Models.Address", "Address")
                        .WithMany("ProviderSettlements")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_ProviderSettlements_Addresses");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Repositories.Models.SourceTransferPolicy", b =>
                {
                    b.HasOne("Repositories.Models.Address", "SourceAddress")
                        .WithMany("SourceTransferPolicies")
                        .HasForeignKey("SourceAddressId")
                        .IsRequired();

                    b.Navigation("SourceAddress");
                });

            modelBuilder.Entity("Repositories.Models.SourceTransferSchedule", b =>
                {
                    b.HasOne("Repositories.Models.SourceTransferPolicy", "SourceTransferPolicy")
                        .WithMany("SourceTransferSchedules")
                        .HasForeignKey("SourceTransferPolicyId")
                        .IsRequired();

                    b.Navigation("SourceTransferPolicy");
                });

            modelBuilder.Entity("Repositories.Models.TransferLedgerEntry", b =>
                {
                    b.HasOne("Repositories.Models.TransferWorkflow", "TransferWorkflow")
                        .WithMany()
                        .HasForeignKey("TransferWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransferLedgerEntries_TransferWorkflow");

                    b.Navigation("TransferWorkflow");
                });

            modelBuilder.Entity("Repositories.Models.TransferWorkflow", b =>
                {
                    b.HasOne("Repositories.Models.Address", "DestinationAddress")
                        .WithMany("TransferWorkflowDestinationAddresses")
                        .HasForeignKey("DestinationAddressId")
                        .IsRequired();

                    b.HasOne("Repositories.Models.DestinationTransferRule", "DestinationTransferRule")
                        .WithMany()
                        .HasForeignKey("DestinationTransferRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Repositories.Models.Address", "SourceAddress")
                        .WithMany("TransferWorkflowSourceAddresses")
                        .HasForeignKey("SourceAddressId")
                        .IsRequired();

                    b.Navigation("DestinationAddress");

                    b.Navigation("DestinationTransferRule");

                    b.Navigation("SourceAddress");
                });

            modelBuilder.Entity("Repositories.Models.TransferWorkflowStatusHistory", b =>
                {
                    b.HasOne("Repositories.Models.TransferWorkflow", "TransferWorkflow")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TransferWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransferWorkflowStatusHistory_TransferWorkflow");

                    b.Navigation("TransferWorkflow");
                });

            modelBuilder.Entity("Repositories.Models.Address", b =>
                {
                    b.Navigation("ConsumptionReadings");

                    b.Navigation("DailyEnergyBalances");

                    b.Navigation("DestinationTransferRules");

                    b.Navigation("InverterInfos");

                    b.Navigation("InverterReadings");

                    b.Navigation("ProviderSettlements");

                    b.Navigation("SourceTransferPolicies");

                    b.Navigation("TransferWorkflowDestinationAddresses");

                    b.Navigation("TransferWorkflowSourceAddresses");
                });

            modelBuilder.Entity("Repositories.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("Repositories.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");
                });

            modelBuilder.Entity("Repositories.Models.InverterInfo", b =>
                {
                    b.Navigation("InverterReadings");
                });

            modelBuilder.Entity("Repositories.Models.SourceTransferPolicy", b =>
                {
                    b.Navigation("DestinationTransferRules");

                    b.Navigation("SourceTransferSchedules");
                });

            modelBuilder.Entity("Repositories.Models.TransferWorkflow", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
